version: '3'

networks:
  tmail:

services:
  cyrus:
    container_name: cyrus
    image: cyrus-local
    environment:
      - CYRUS_PWD=cyrus
    ports:
      - 993:993
      - 143:143
      - 8008:8008
      - "25:25"
      - "465:465"
      - "587:587"
    volumes:
      - ./cyrus/imapd.conf:/etc/imapd.conf
      - ./cyrus/saslauthd:/etc/default/saslauthd
      - ./cyrus/cyrus.conf:/etc/cyrus.conf
      - ./postfix/:/etc/postfix/
    networks:
      - tmail

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - tmail
    depends_on:
      - cyrus
